top25 = {
    "Apple Inc.": "AAPL",
    "Microsoft Corp.": "MSFT",
    "Amazon.com Inc.": "AMZN",
    "Tesla Inc.": "TSLA",
    "Alphabet Inc. Class A": "GOOGL",
    "Facebook Inc. Class A": "FB",
    "Alphabet Inc. Class C": "GOOG",
    "NVIDIA Corporation": "NVDA",
    "Berkshire Hathaway Inc. Class B": "BRK.B",
    "JPMorgan Chase and Co": "JPM",
    "Johnson and Johnson": "JNJ",
    "UnitedHealth Group Inc.": "UNH",
    "Home Depot Inc.": "HD",
    "Visa Inc.": "V",
    "Bank of America Corp.": "BAC",
    "Procter and Gamble Co.": "PG",
    "Mastercard Inc.": "MA",
    "Walt Disney Co.": "DIS",
    "Adobe Inc.": "ADBE",
    "Netflix Inc.": "NFLX",
    "Paypal Holdings Inc.": "PYPL",
    "Salesforce.com Inc.": "CRM",
    "Exxon Mobil Corp.": "XOM",
    "Comcast Corp. Class A": "CMCSA",
    "Pfizer Inc.": "PFE",
}
